# Generated by Django 5.1.6 on 2025-02-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
