# Generated by Django 5.1.6 on 2025-03-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_review_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
