# Generated by Django 5.1.6 on 2025-03-03 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
