# Generated by Django 5.1.7 on 2025-03-08 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_booking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('provider', 'date', 'time')},
        ),
    ]
